name: ​🐞 Bug
description: Report an issue to help us improve the workflow.
title: "[BUG] <concise description>"
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A brief description of the issue.
    validations:
      required: false
  - type: input
    attributes:
      label: Action Version
      description: Write verion number in which you are facing bug.
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Please add screenshots if applicable
    validations:
      required: false
  - type: dropdown
    id: browsers
    attributes:
      label: Platform?
      multiple: false
      options:
        - Ubuntu
        - macOS
        - Windows
  - type: checkboxes
    id: no-duplicate-issues
    attributes:
      label: "Checklist"
      description: "By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Anmol-Baranwal/DevSync/blob/main/CODE_OF_CONDUCT.md)"
      options:
        - label: "I have checked the existing [issues](https://github.com/Anmol-Baranwal/DevSync/issues?q=is%3Aissue+)"
          required: true
        - label: "I have read the [Contributing Guidelines](https://github.com/Anmol-Baranwal/DevSync/blob/main/Contributing.md)"
          required: true
        - label: "I am willing to work on this issue (optional)"
          required: false
