name: Feature Request 💡
description: Have any new idea or new feature to improve the workflow? Please suggest!
title: "[Feature] <write a small description here>"
labels: ["enhancement", "goal: new-feature"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the feature.
    validations:
      required: true
  - type: textarea
    id: usecase
    attributes:
      label: Useful Examples
      description: Provide an example use case for your suggested feature.
    validations:
      required: true
  - type: checkboxes
    id: no-duplicate-issues
    attributes:
      label: "Checklist"
      description: "By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Anmol-Baranwal/DevtoGitHub/blob/main/CODE_OF_CONDUCT.md)"
      options:
        - label: "I have checked the existing [issues](https://github.com/Anmol-Baranwal/DevtoGitHub/issues?q=is%3Aissue+)"
          required: true
        - label: "I have read the [Contributing Guidelines](https://github.com/Anmol-Baranwal/DevtoGitHub/blob/main/Contributing.md)"
          required: true
        - label: "I am willing to work on this issue (optional)"
          required: false
